### ISSUE TITLE
Question about parse to datetime

### ISSUE THREAD

**Issue by Vitorspk** [goyalmohit/acr-cleanup#1]
```
Exception calling "ParseExact" with "3" argument(s): "String '1' was not recognized as a valid DateTime."
At /home/xxx/workspace/acr-cleanup/acr-cleanup.ps1:62 char:9
+         $RepositoryTagBuildDay = [datetime]::ParseExact($repositoryta ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : FormatException
```

follow my command to execute
`.\acr-cleanup.ps1 -ServicePrincipalId xxx -ServicePrincipalPass xxx -ServicePrincipalTenant xxx -AzureRegistryName xxx -NoOfDays 90
`
do you know why i get this error when try to run this command?

**Comment by goyalmohit** [comment]
Can you share the naming structure of your docker images and the PowerShell culture information.

**Comment by Vitorspk** [comment]
> Can you share the naming structure of your docker images and the PowerShell culture information.

Im using your powershell script not change any line of code and run this DockerFile with my build arg options from my azure credentials.

```
FROM ubuntu:trusty

ARG SERVICEPRINCIPALID
ARG SERVICEPRINCIPALPASS
ARG SERVICEPRINCIPALTENANT
ARG AZUREREGISTRYNAME
ARG NOOFDAYS

ENV SERVICEPRINCIPALID $SERVICEPRINCIPALID
ENV SERVICEPRINCIPALPASS $SERVICEPRINCIPALPASS
ENV SERVICEPRINCIPALTENANT $SERVICEPRINCIPALTENANT
ENV AZUREREGISTRYNAME $AZUREREGISTRYNAME
ENV NOOFDAYS $NOOFDAYS

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        apt-utils \
        ca-certificates \
        curl \
        apt-transport-https \
    && rm -rf /var/lib/apt/lists/*
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/14.04/prod.list | tee /etc/apt/sources.list.d/microsoft.list
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
	powershell

COPY . /app

WORKDIR /app/

CMD [ "pwsh" ]

```

do you have any DockerFile image?

**Comment by goyalmohit** [comment]
Sorry for the late reply. I am not sure why do you need dockerfile / docker image. This is a plain PowerShell script which you can run from convenience of your desktop/server/docker container. Also, a little tweak may be required to run it using PSCore version.

**Comment by Vitorspk** [comment]
I have created an dockerfile to run it on my kubernetes cluster like cronjob to clean my azure container registry after 90 days.

that the reason to do dockerfile. Please can you help me with this error?

**Comment by goyalmohit** [comment]
I created an ubuntu VM, installed PSCore and ran the script without any code changes. It runs fine:

![powershell core run output](https://user-images.githubusercontent.com/17618049/50307513-a6c90500-04be-11e9-9258-523612b6e7a1.JPG)

Only case it throws error is if the naming scheme for docker images is not like in the screenshot. If it differs, then you need to modify the script a little. It will be great if you can share docker image naming scheme in your case.

**Comment by Vitorspk** [comment]
Alright, thanks advanced.

i will share docker image soon was possible here.

**Comment by robertmarks** [comment]
I've also run into the issue with datetime
`Exception calling "ParseExact" with "3" argument(s): "String was not recognized as a valid DateTime."`

I've tried running it on Windows with Az CLI and Mac with Az CLI

ACR images are named in the following convention: `my-service:PR-3-1`

Edit: obviously this isn't going to work in my use case as we're not using the naming method you are - thanks though 👍

**Comment by goyalmohit** [comment]
I hope that there are no further issues with the script itself or you have found a better way more suitable for your use case. Please raise a new issue if still need some more information.
